# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
- name: PROJECT_NAME
  value: azure-pipeline-demo 

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'dist.p12'
    keychain: 'temp'
- task: InstallAppleProvisioningProfile@1
  displayName: 'Install Profiles iOS'
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'azuredemodist.mobileprovision'
- task: DownloadSecureFile@1
  name: apiKey
  displayName: 'Download AuthKey_{KeyID}.p8 file'
  inputs:
    secureFile: 'AuthKey_$(API_KEY_ID).p8'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      xcodebuild archive -project '$(PROJECT_NAME).xcodeproj' -scheme '$(PROJECT_NAME)' -sdk iphoneos -archivePath $(PROJECT_NAME).xcarchive   
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      xcodebuild -exportArchive -archivePath $(PROJECT_NAME).xcarchive -exportPath $(PROJECT_NAME) -exportOptionsPlist ExportOptions.plist
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir ~/.private_keys 
      mv $(apiKey.secureFilePath) ~/.private_keys
      xcrun altool \
      --upload-app \
      -f $(PROJECT_NAME)/$(PROJECT_NAME).ipa \
      -t ios \
      --apiKey $API_KEY_ID \
      --apiIssuer $API_KEY_ISSUER_ID \
      --verbose \
